### ISSUE TITLE
Cannot read property 'resurrectTimeout' of undefined

### ISSUE THREAD

**Issue by kulakowka** [elastic/elasticsearch-js#1122]
Greetings! 

I found an error in the code:
 
https://github.com/elastic/elasticsearch-js/blob/1b638d69925d64a7402617265e739dc85b316ca1/lib/pool/ConnectionPool.js#L107

```js
    const connection = this.connections.find(c => c.id === this.dead[0])

    if ((opts.now || Date.now()) < connection.resurrectTimeout) {
      debug('Nothing to resurrect')
      callback(null, null)
      return
    }
```

If the connection is not found. Then the code will throw an error further: **Cannot read property 'resurrectTimeout' of undefined**

I just got a lot of such errors in production. 

<img width="922" alt="Screen Shot 2020-03-22 at 8 57 21 AM" src="https://user-images.githubusercontent.com/557190/77243449-2a6e2600-6c1b-11ea-91ec-e3b78391ceb0.png">

**Comment by delvedor** [comment]
Hello! Thank you for reporting this!
It looks like the issue you have encountered is hiding another bug.
That code should always have a "valid" dead connection because few lines above, we are checking that the `dead` array contains something.
So very likely, the `dead` array is not cleaned up properly.

Which version of the client and Elasticsearch are you using?
Where are you running Elasticsearch?
Can you paste here the options you are using for configuring the client?

Thanks!

**Comment by kulakowka** [comment]
Client config: 
```yml
elastic:
  client:
    maxRetries: 6
    requestTimeout: 10000
    sniffOnConnectionFault: true
    sniffOnStart: true
    nodes:
      - http://***.***.**.**:9201
      - http://***.***.**.**:9201
      - http://***.***.**.**:9201
    agent:
      keepAlive: false
      keepAliveMsecs: 1000
      maxSockets: 256
      maxFreeSockets: 256
```

Client version:

```json
{
  "@elastic/elasticsearch": "^7.6.1"
}
```

Elastic version:

```json
{
  "name" : "mvs-elastic-01-mvs",
  "cluster_name" : "mvs",
  "cluster_uuid" : "-q1EWefBQa2auCjGwMLnfw",
  "version" : {
    "number" : "7.4.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
    "build_date" : "2019-10-28T20:40:44.881551Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

We also observe periodically errors: **There are no living connections**

Perhaps the reason is this?
