### ISSUE TITLE
Code snippets in the Documentation without a monospace fallback

### ISSUE THREAD

**Issue by penge** [elastic/elasticsearch-js#1146]
## 🐛 Bug Report

Code snippets in the Documentation at https://www.elastic.co/guide/index.html don't have a correct fallback font - font that would be used if none of the monospaced fonts is present. Right now, the fallback is `sans-serif`, but should be `monospace`.

## To Reproduce

Open:

- https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html
- https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format.html

In the case of Chrome OS, the code snippet would have `sans-serif` font. It would look like:

![before](https://user-images.githubusercontent.com/907255/78704756-aac7a300-790c-11ea-9496-9a15dba3b550.png)

## Expected behavior

Expected is to have a `monospace` fallback. It would look like this:

![after](https://user-images.githubusercontent.com/907255/78704582-591f1880-790c-11ea-9d2d-3dbf07b84354.png)

This is easy to fix. Change the style **from:**

```css
#guide .prettyprint span {
    font-family: Consolas,Menlo,DejaVu Sans Mono,Bitstream Vera Sans Mono,Lucida Console;
}
```

**To:**

```css
#guide .prettyprint span {
    font-family: Consolas,Menlo,DejaVu Sans Mono,Bitstream Vera Sans Mono,Lucida Console,monospace;
}
```

This would use a Fixed-width font (monospace) based on the OS. In the case of Chrome OS, it would be `Cousine`. Elsewhere it could be `Courier New`. Right now, the fallback is `sans-serif` because that's how it's defined in:

```css
guide * {
  font-family: Inter,sans-serif;
}
```

## Your Environment

- *os*: Chrome OS, Version 80
