### ISSUE TITLE
Failing "Should not retry if the body is a stream"

### ISSUE THREAD

**Issue by penge** [elastic/elasticsearch-js#1154]
## 🐛 Bug Report

Failing test found. Only on CI.

Logs: https://github.com/elastic/elasticsearch-js/pull/1142/checks?check_run_id=579324431

```
# Subtest: Should not retry if the body is a stream

found: 0
wanted: 1
compare: ===
at:
    line: 667
    column: 9
    file: test/unit/transport.test.js
stack: |
    test/unit/transport.test.js:667:9
    onResponse (lib/Transport.js:157:16)
    ClientRequest.<anonymous> (lib/Connection.js:94:9)
```
