### ISSUE TITLE
query @timestamp field

### ISSUE THREAD

**Issue by RichardJohnn** [elastic/elasticsearch-js#419]
when I try to query a `@timestamp` field using this `body` 
```
      query.body =
        query:
          filtered:
            filter:
              range:
                "@timestamp":
                  gte: params.beginDate
                  lt:  params.endDate
```
I don't get any results.  If I change the field on the log to `timestamp` and update this query, I find the records.  `curl`ing like 
```
curl -X GET 'http://localhost:9200/_all/logFiles/_search?pretty' -d '{
    "query": {
        "filtered": {
            "query": {
                "match_all": {}
            },
            "filter": {
                "range": {
                    "@timestamp": {
                        "gte": "16/06/2015",
                        "lt":  "17/06/2017",
                        "format": "dd/MM/yyyy"
                    }
                }
            }
        }
    }
}
```
finds the records AOK.  Any tips?
