### ISSUE TITLE
Supplying multiple host urls to node param results in NoLivingConnectionsError

### ISSUE THREAD

**Issue by lsnyder** [elastic/elasticsearch-js#829]
## 🐛 Bug Report

Specifying multiple ```nodes``` as an array of strings results in a ```NoLivingConnectionsError```

## To Reproduce

1. Instantiate Client with multiple urls specified in ```node```
2. Call ```client.search()```

Paste your code here:

```js
const { Client } = require('@elastic/elasticsearch')

var client = new Client({
  node:[
        "https://<username>:<password>@<ip1><port>",
        "https://<username>:<password>@<ip2><port>",
        "https://<username>:<password>@<ip3><port>",
  ]
})

client.search({})
   .then(res => console.log(res))
   .catch(err => console.log(err))


{ NoLivingConnectionsError: There are not living connections
    at makeRequest (/Workspace/svc-jetson/node_modules/@elastic/elasticsearch/lib/Transport.js:117:25)
    at onResponse (/Workspace/svc-jetson/node_modules/@elastic/elasticsearch/lib/Transport.js:202:21)
    at ClientRequest.request.on.err (/Workspace/svc-jetson/node_modules/@elastic/elasticsearch/lib/Connection.js:111:9)
    at ClientRequest.emit (events.js:193:13)
    at ClientRequest.EventEmitter.emit (domain.js:481:20)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at TLSSocket.EventEmitter.emit (domain.js:481:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) name: 'NoLivingConnectionsError', meta: undefined }

```

Instantiating the client with any **one** of the url's either as:
```
node:["https://<username>:<password>@<ip1><port>"]
```
```
node: "https://<username>:<password>@<ip1><port>"
```

results in a successful search request. It is when specifying multiple that the above error occurs. The ConnectionPool looks correct when inspecting the client, and the ```_auth``` property is set correctly.

```
Client {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  serializer: Serializer {},
  connectionPool:
   ConnectionPool {
     connections:
      Map {
        'https://<ip1><port>/' => [Object],
        'https://<ip2><port>/' => [Object],
        'https://<ip3><port>/' => [Object] },
     dead: [],
     selector: undefined,
     _auth:
      { username: 'myusername', password: 'mypassword' },
     _ssl: null,
     _agent: null,
     resurrectTimeout: 120000,
     resurrectTimeoutCutoff: 5,
     pingTimeout: 3000,
     Connection:
      { [Function: Connection] statuses: [Object], roles: [Object] },
     emit: [Function: bound ],
     _sniffEnabled: false,
     resurrectStrategy: 1 },
```

## Expected behavior

Specifying an array of urls should result in a Connection for each and not result in ```NoLivingConnectionsError```

According to the docs the above format is correct, and seeing how each host url works individually, I'm failing to see an issue in my config.

Is 5.6.16-rc.1 not compatible with elastic 5.4.1? The docs say to use
```@elastic/elasticsearch@5``` but installing that is not an option via npm.

## Your Environment

- *node version*: 11.14.0
- `@elastic/elasticsearch` 5.6.16-rc.1
- *os*: Mac
- *elasticsearch*: 5.4.1
- nginx running in front of elastic

**Comment by delvedor** [comment]
Hello!
I've created this code to reproduce your issue:

```js
'use strict'

const intoStream = require('into-stream')
const { Client, Connection } = require('@elastic/elasticsearch')

class MyConnection extends Connection {
  request (params, callback) {
    const stream = intoStream(JSON.stringify({ hello: 'world' }))
    stream.statusCode = 200
    stream.headers = { 'content-type': 'application/json' }
    callback(null, stream)
  }
}

const client = new Client({
  nodes: [
    'https://user:pwd@localhost:9200',
    'https://user:pwd@localhost:9201',
    'https://user:pwd@localhost:9202'
  ],
  Connection: MyConnection
})

client.search(console.log)
```

It works as expected, which means that something external to the client code causes the issue.
Can you create a repository to reproduce the problem?

**Comment by delvedor** [comment]
> Is 5.6.16-rc.1 not compatible with elastic 5.4.1? The docs say to use
`@elastic/elasticsearch@5` but installing that is not an option via npm.

This is happening because the client is still in RC, and npm does not support pre-releases.
The only way to install it, for now, is `npm i @elastic/elasticsearch@5.6.16-rc.2`. Sorry for the inconvenience!

**Comment by lsnyder** [comment]
@delvedor Thanks for the reply! So, I had attempted to repro yesterday by running a cluster locally and received the ```NoLivingConnectionsError``` again. I just tried your code above and it works. The difference being in your code above you specified a custom connection with ```MyConnection```. Without specifying the connection are you able to repro the ```NoLivingConnectionsError```?

**Comment by delvedor** [comment]
I've created a 3 nodes cluster with this `docker-compose`:
```yml
version: '3.2'

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - esnet

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  esnet:
```

The code now looks like this:
```js
'use strict'

const { Client } = require('./index')

const client = new Client({
  nodes: [
    'http://localhost:9200',
    'http://localhost:9201',
    'http://localhost:9202'
  ]
})

client.search({}, console.log)
```

Still no issue at all.
Can you please create a repository to reproduce the issue?
